# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: p4/server/v1/config.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'p4/server/v1/config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19p4/server/v1/config.proto\x12\x0cp4.server.v1\"E\n\nSetRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\x04\x12$\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x14.p4.server.v1.Config\"\r\n\x0bSetResponse\"\x1f\n\nGetRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\x04\"3\n\x0bGetResponse\x12$\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x14.p4.server.v1.Config\"4\n\x06\x43onfig\x12*\n\x06stream\x18\x01 \x01(\x0b\x32\x1a.p4.server.v1.StreamConfig\"\x97\x01\n\x0cStreamConfig\x12G\n\x0f\x65rror_reporting\x18\x01 \x01(\x0e\x32..p4.server.v1.StreamConfig.ErrorReportingLevel\">\n\x13\x45rrorReportingLevel\x12\x0c\n\x08\x44ISABLED\x10\x00\x12\x0b\n\x07\x45NABLED\x10\x01\x12\x0c\n\x08\x44\x45TAILED\x10\x02\x32\x86\x01\n\x0cServerConfig\x12:\n\x03Set\x12\x18.p4.server.v1.SetRequest\x1a\x19.p4.server.v1.SetResponse\x12:\n\x03Get\x12\x18.p4.server.v1.GetRequest\x1a\x19.p4.server.v1.GetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p4.server.v1.config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETREQUEST']._serialized_start=43
  _globals['_SETREQUEST']._serialized_end=112
  _globals['_SETRESPONSE']._serialized_start=114
  _globals['_SETRESPONSE']._serialized_end=127
  _globals['_GETREQUEST']._serialized_start=129
  _globals['_GETREQUEST']._serialized_end=160
  _globals['_GETRESPONSE']._serialized_start=162
  _globals['_GETRESPONSE']._serialized_end=213
  _globals['_CONFIG']._serialized_start=215
  _globals['_CONFIG']._serialized_end=267
  _globals['_STREAMCONFIG']._serialized_start=270
  _globals['_STREAMCONFIG']._serialized_end=421
  _globals['_STREAMCONFIG_ERRORREPORTINGLEVEL']._serialized_start=359
  _globals['_STREAMCONFIG_ERRORREPORTINGLEVEL']._serialized_end=421
  _globals['_SERVERCONFIG']._serialized_start=424
  _globals['_SERVERCONFIG']._serialized_end=558
# @@protoc_insertion_point(module_scope)
